### ISSUE TITLE
Feature request: minimum-cp constraint or penalty

### ISSUE THREAD

**Issue by klausbu** [jxjo/Xoptfoil2#2]
Feature request:

Is there a way to set minimum-cp (from the xflr5 OpPoint view F5) as a constraint or penalty to be above a certain value (maybe for a defined AOA range)?

There has been a discussion about it and its implementation related to the original xoptfoil but the implementation never happened:

See: https://www.rcgroups.com/forums/showthread.php?2095696-XoptFoil-airfoil-optimization-with-XFoil/page29 #431, #432

The limitation of the suction peak is one aspect but the cp-min can also be above the back of the foil, in this case a "rooftop" can be a result, see picture under #432 on the very right.

**Comment by jxjo** [comment]
Hello Klaus,

... thank you for the link into the rcgroups discussion (which reflects also my current 'state' of the topic) 

I would suggest 2 common approaches:

1. Adding a new curvature constraint 'max_le_curvature' to define the maximum curvature at leading edge. There is already a 'max_te_curvature'  to limit curvature artefacts at trailing edge. This constraint would also support to get not too 'sharp' leading edges - and indirectly control the suction peak. This extension is quite straight forward as there is already some leading edge curvature handling to achieve 'curvature continuity' when applying bezier or hicks-henne on top and bottom side. 

2. Adding a new operating point target type 'target_cpmin' which defines the minimum cp value at this operating point. As the default handling for optimization targets is 'allow_improved_targets', the optimzer would try to achieve this 'target_cpmin' value or higher.  This extension needs a little more time and testing to adjust the behaviour to the other 'optimization types' ...

Would this fit to your thoughts? 

regards

**Comment by klausbu** [comment]
Yes, it would fit and should be very beneficial.

**Comment by jxjo** [comment]
Hello Klaus, 

... after thinking about it again: Introducing targets like 'cp_min' wouldn't be in the sense in which Xoptfoil is intended: Design an airfoil by its polars. The shape of the suction peak can be 'controlled' by the shape of the polar at higher cl ...

Hope this is Ok for you ... !
