### ISSUE TITLE
Ubuntu 20.04 compile error: Fatal Error: Cannot open module file ‘optimization_util.mod

### ISSUE THREAD

**Issue by klausbu** [jxjo/Xoptfoil2#3]
**I get a compile error on Ubuntu 20.04**

`[ 47%] Building Fortran object CMakeFiles/MYOBJLIB.dir/src/fortran/particle_swarm.f90.o
/usr/bin/gfortran -DPACKAGE_VERSION=\"1.70beta\"  -fpic -O2 -fopenmp -DOPENMP=1 -cpp -DUNIX=1  -c /home/klaus/Programme/Xoptfoil2-main/src/fortran/particle_swarm.f90 -o CMakeFiles/MYOBJLIB.dir/src/fortran/particle_swarm.f90.o
/home/klaus/Programme/Xoptfoil2-main/src/fortran/particle_swarm.f90:63:9:

   63 |     use optimization_util,    only : init_random_seed, initial_designs,             &
      |         1
Fatal Error: Cannot open module file ‘optimization_util.mod’ for reading at (1): Datei oder Verzeichnis nicht gefunden
compilation terminated.
make[2]: *** [CMakeFiles/MYOBJLIB.dir/build.make:231: CMakeFiles/MYOBJLIB.dir/src/fortran/particle_swarm.f90.o] Fehler 1
make[2]: Verzeichnis „/home/klaus/Programme/Xoptfoil2-main/build“ wird verlassen
make[1]: *** [CMakeFiles/Makefile2:89: CMakeFiles/MYOBJLIB.dir/all] Fehler 2
make[1]: Verzeichnis „/home/klaus/Programme/Xoptfoil2-main/build“ wird verlassen
make: *** [Makefile:136: all] Fehler 2
`

**Comment by thomasbeh** [comment]
Hallo Klaus,
dieses Problem trat bei mir auch auf. Ich weiß nicht, welche Softare-Version Du Dir von hier gezogen hast denn soweit ich weiß, ist das Problem behoben. Die Ursache war eigentlich, zumindest bei mir, simpel: Dateiendungen der folgenden Dateien im Ordner fortran:
optimization_uitl.**F90** muss heißen:  optimization_uitl.**f90**
dito
input_read.F90 muss heißen: input_read.f90
Windows ist es egal, ob die Dateiendungen groß oder klein geschrieben sind, Linux aber nicht.

Danach komplierte es bei mir fehlerfrei. Nur Mut, ich habe Xoptfoil2 unter Mint (abgeleitet von Ubuntu) ziemlich schnell zum Laufen bekommen.
Beste Grüße
Thomas

**Comment by klausbu** [comment]
Danke, genau das war das Problem

**Comment by jxjo** [comment]
Thank You Thomas!
(now you are really rehabilitated 😉)
