### ISSUE TITLE
jatroyam

### ISSUE THREAD

**Issue by jatroyam** [jxjo/Xoptfoil2#6]
hello,

Congratulations for your hard work !!!

I've found a little bug in 'subroutine eval_geometry_violations' in file 'eval_constraints.f90' of program version 1.0.1.

maxc should be replaced by maxt at line number 169.

! if (c%min_thickness /= NOT_DEF_D .and. maxc < c%min_thickness) then    ! BUG
  if (c%min_thickness /= NOT_DEF_D .and. maxt < c%min_thickness) then

best regards.

JA Troya

**Comment by jxjo** [comment]
Hello JA Troya,
... oh - is it so important if it's 't' or 'c'? 
Just kidding ...

Super - thanks a lot for your perfect investigation! 👍 
Fix will be in next version. 
Don't hesitate, if you have suggestions for improvement...

Best rergards
Jochen
