### ISSUE TITLE
Error at line 377

### ISSUE THREAD

**Issue by goney3** [jxjo/Xoptfoil2#9]
I tried running the optimized airfoil through Xoptfoil2 at a much lower Re (100,000) and I managed to crash it... oops.

![image](https://github.com/jxjo/Xoptfoil2/assets/19561317/56f1d662-5257-42b0-9627-08e7fec502ce)

Input file:
```
! Easy going examaple ...
!
! Optimize min cd while keeping glide ratio of SD7003 at Reynolds 400,000 
! The optimized airfoil should have 8% thickness  
!

&optimization_options
  airfoil_file     = 'Opt5.dat'
  shape_functions  = 'hicks-henne'				! camb-thick, bezier, hicks-henne
  show_details = .false.						! only minimum output on screen
/  

&particle_swarm_options
  convergence_profile = 'exhaustive'                   	! 'quick' for fast convergence (results) 
/

&operating_conditions

  dynamic_weighting      = .true.                   ! activate dynamic weighting during optimization
  allow_improved_target  = .true.                   ! results are allowed to be better than target 
  
  re_default       = 100000						! use this Reynolds number for operating points
  noppoint         = 2

  op_mode(1) = 'spec-cl'						! Specifiy operating point based on cl-value						
  op_point(1) = 0.2
  optimization_type(1) = 'target-moment'
  target_value(1) = 0.0000  

  op_mode(2) = 'spec-cl'
  op_point(2) = 0.7								! glide ratio cl/cd at cl = 0.7
  optimization_type(2) = 'target-moment'         !   
  target_value(2) = -0.0 						! keep the current value of SD7003
/

&geometry_targets
  ngeo_targets    = 2
  target_type(1)  = 'Camber'
  target_value(1) = 0.0200							! we want an airfoil family with ths camber 
  target_type(2)  = 'Thickness'
  target_value(2) = 0.18
/  
```

**Comment by jxjo** [comment]
Hello Keith,

... this is strange! 
;-) 

You didn't run 2 XO2 at the same time in the same directory? 
And I assume the error is not reproducible?

Could you provide the Opt5.dat airfoil? 

best regards

Jochen

**Comment by goney3** [comment]
[Opt5.txt](https://github.com/user-attachments/files/15831320/Opt5.txt)
Hi Jochen,
I've been thinking about this error, I am wondering if it has to do with me running this on my Synology NAS drive folder? Maybe a network hiccup caused it to not be able to read/write itself while running? I haven't had it reproduceable since... :\

**Comment by jxjo** [comment]
Hello Keith, 

... yes, that could be the reason! ;-) 
The 'write' is done some microseconds after 'read' (it is the 'run_control' file) 
The file handling of remote file on servers can get some timing issues ...
